### ISSUE TITLE
Progress on the spec

### ISSUE THREAD

**Issue by cabanier** [immersive-web/model-element#78]
There haven't been updates to the spec in quite a while and the current one doesn't reflect decisions that were made since (ie make <model> derive from <mediaelement>)
/facetoface how can we make more progress on the model tag spec?

**Comment by DRx3D** [comment]
Rather than making progress on writing a specification document, there needs to be 

- the domain of applicability of this element
    - will this be for thumbnail models
    - will multiple models be integrated
    - will the element support animation
    - will the element support lighting
- an explanation of what this spec would provide that cannot be already done
- why existing solutions cannot be used (e.g., model-viewer)
- an explanation of how this plans on handling multiple models, animation, and lighting
- how the element will keep up with changes to other specs (file formats) that supply the models
- What happens when the web community finds that <model-element> does not support a needed/desired feature that is included in a library.

Note that it is fine to exclude certain capabilities, it should just be stated so.

**Comment by npolys** [comment]
Yes, related to # 86

The document should justify the approach and compare and contrast to the demonstrated standards already in this space and described by W3C Community Groups (and Class A Liaisons)... specifically the ISO-IEC Standards of X3D. With a nice alignment to the DOM, CSS, HTML, glTF2, and WebAudio, X3D
Version 4 was just ratified through the full standard process and voting by National Bodies:

https://web3d.org/x3d4
see also: https://webx3d.org/

The standard is implemented by two open source javascript libraries:
X3DOM https://www.x3dom.org/ (WebXR supported)
X_ITE https://github.com/create3000/x_ite/wiki

The MIME types for X3D are model/x3d+xml, model/x3d+binary, and model/x3d+vrml. The Internet Assigned Numbers Authority (IANA) has approved model/x3d+xml as the primary MIME media type for X3D media in XML encoding.

In the Metaverse Standards Forum 3D Web Interoperability Group, we are discussing the X3D pattern of of url and uris for different kinds of linked content and experiences; also we are looking at the conformance mechanism inherent in the Profiles and Components that enables different levels of interactive 3D functionality to be specified.


We believe that we should work together to update this spec

https://www.rfc-editor.org/rfc/rfc2077.html

**Comment by zachernuk** [comment]
I feel like we've made a lot of headway in the last 6 months - It seems like the ~45 minutes per month that we effectively end up using to talk about this feature is insufficient to resolve the details necessary to get a properly-specified feature. 

I'd love to establish a more focused meeting - open to all - with a more regular cadence, so that people aren't coming back to the issues with four weeks of time to make up for between discussion. AFAIK, the initial WebXR spec was worked out with a more frequent schedule as well, so there is a precedent.

/agenda

**Comment by zachernuk** [comment]
closing, since we have the request with the chairs to do more!
